version: '3.4'
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    volumes:
      - ./db/pga4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5454
    restart: unless-stopped