# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8700

# ===============================
# = Actuator.
# ===============================
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  server:
    port: 9001

# ===============================
# = Locale.
# ===============================
ui:
  locale: en