# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8700

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    org:
      springframework:
        web: ERROR

        
