# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8700
        
